version: '3.7'
services:
  kanye-app:
    container_name: kanye-php
    restart: unless-stopped
    build:
      args:
        user: kanye
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - kanye-laravel
  kanye-nginx:
    image: 'nginx:latest'
    container_name: kanye-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/templates/:/etc/nginx/templates/
    environment:
      BACKEND: kanye-php
    ports:
      - '8123:80'
    depends_on:
      - kanye-app
    networks:
      - kanye-laravel
networks:
  kanye-laravel:
    driver: bridge